invoice_django/urls.py
from django.contrib import admin
from django.urls import path, include
from invoice_system.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('',  dashboardView, name='dashboard_url'),
    path('fletpercjellja_create/', FletpercjelljaCV.as_view(), name='fletpercjellja_create_url'),
    path('fletpercjellja_listview/', FletpercjelljaLV.as_view(), name='fletpercjellja_listview_url'),
    path('fletpercjellja_detail/<slug:f_id>/', fletpercjellja_detail_view, name='fletpercjellja_detail_url'),

    path('produkt_create/', ProductCV.as_view(), name='produkt_create_url'),
    path('produkt_listview/', produkt_listview, name='produkt_listview_url'),
    path('produkt_update/<slug:pk>/', ProductUV.as_view(), name='produkt_update_url'),
    path('produkt_detail/<slug:pk>/', ProductDV.as_view(), name='produkt_detail_url'),
     path('produkt_delete/<slug:pk>/', ProductDelete.as_view(), name='produkt_delete_url'),

]

invoice_system/models.py
from django.db import models
from django.urls import reverse
import datetime


class Product(models.Model):
	UNIT_CHOICES = (
		('Cope', 'Cope'),
		('kg', 'kg'),
		('m', 'm'),
		('m^2', 'm^2'),
	)
	product_id = models.CharField(max_length=50, primary_key=True)
	product_name = models.CharField(max_length=50)
	product_desc = models.CharField(max_length=100, null=True, blank=True)
	product_price = models.DecimalField(max_digits=10, decimal_places=2)
	product_unit = models.CharField(max_length=5, choices=UNIT_CHOICES, default='Cope')
	
	class Meta:
		ordering = ['product_id']


	@property
	def quantity(self):
		quantity = 0

		for i in Shitje.objects.filter(product=self.product_id):
			quantity -= i.shitje_quantity

		for i in Hyrje.objects.filter(product=self.product_id):
			quantity += i.hyrje_quantity

		return quantity

	@property
	def hyrje(self):
		hyrje = 0

		for i in Hyrje.objects.filter(product=self.product_id):
			hyrje += i.hyrje_quantity

		return hyrje

	@property
	def dalje(self):
		dalje = 0

		for i in Shitje.objects.filter(product=self.product_id):
			dalje += i.shitje_quantity

		return dalje

	def __str__(self):
		return f'{self.product_id}'

	def get_absolute_url(self):
		return reverse('produkt_detail_url', kwargs={'pk': self.pk})






class Fletpercjellja(models.Model):
	fletpercjellja_id = models.CharField(max_length=4, primary_key=True)
	fletpercjellja_data = models.DateTimeField(default=datetime.datetime.now)
	fletpercjellja_verejtje = models.TextField(null=True, blank=True)

	class Meta:
		ordering = ['-fletpercjellja_data']

	@property
	def get_total(self):
		sum = 0.0
		for i in Shitje.objects.filter(fletpercjellja=self.fletpercjellja_id):
			sum += float(i.get_shitje_total)
		return f'{sum:.2f} €'

	def __str__(self):
		return f'{self.fletpercjellja_id}'

	def get_absolute_url(self):
		return reverse('fletpercjellja_detail_url', kwargs={'f_id': self.fletpercjellja_id})


class Shitje(models.Model):
	fletpercjellja = models.ForeignKey(Fletpercjellja, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	shitje_quantity = models.DecimalField(max_digits=10, decimal_places=2)
	shitje_price = models.DecimalField(max_digits=10, decimal_places=2)

	@property
	def get_shitje_total(self):
		return self.shitje_quantity * self.shitje_price

	@property
	def totali(self):
		if self.shitje_quantity != None and self.shitje_price != None:
			total = self.shitje_quantity * self.shitje_price
		else:
			total = 0
			
		return f'{total:.2f}'

	def __str__(self):
		return f'{self.product} - {self.shitje_quantity}'







class FaturaHyrese(models.Model):
	fathyrese_id = models.CharField(max_length=50, primary_key=True)
	fathyrese_data = models.DateTimeField()
	fathyrese_verejtje = models.TextField(null=True, blank=True)

	class Meta:
		ordering = ['fathyrese_id']

	@property
	def get_total(self):
		sum = 0.0
		for i in Hyrje.objects.filter(fathyrese=self.fathyrese_id):
			sum += float(i.get_hyrje_total)
		return f'{sum:.2f} €'

	def __str__(self):
		return f'{self.fathyrese_id}'

class Hyrje(models.Model):
	fathyrese = models.ForeignKey(FaturaHyrese, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	hyrje_quantity = models.DecimalField(max_digits=10, decimal_places=2)
	hyrje_price = models.DecimalField(max_digits=10, decimal_places=2)

	@property
	def get_hyrje_total(self):
		return self.hyrje_quantity * self.hyrje_price

	@property
	def totali(self):
		if self.hyrje_quantity != None and self.hyrje_price != None:
			total = self.hyrje_quantity * self.hyrje_price
		else:
			total = 0
			
		return f'{total:.2f}'

	def __str__(self):
		return f'{self.product} - {self.hyrje_quantity}'

invoice_system/forms.py
from django import forms
from .models import *


class ShitjeForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		self.f_id = kwargs.pop('f_id')
		super(ShitjeForm, self).__init__(*args, **kwargs)
		self.fields['fletpercjellja'] = forms.ModelChoiceField(initial=self.f_id, queryset=Fletpercjellja.objects.all(), label='', widget=forms.Select(attrs={
				"style": "display:none;",
				"id": "fp_select",
				
			}))
	class Meta:
		model = Shitje
		fields = '__all__'
		# exclude = ('fletpercjellja',)


class SearchGetFletpercjellja(forms.Form):
	search = forms.CharField(label="Search", max_length=100)

invoice_system/views.py
from django.shortcuts import render, get_object_or_404
from django import forms
from .models import *
from .forms import *
from django.http import HttpResponseRedirect, Http404
from django.views.generic import (
	View,
	CreateView,
	UpdateView,
	DetailView,
	ListView,
	DeleteView,
	)


def dashboardView(request):
	return render(request, 'invoice_system/dashboard.html')


class FletpercjelljaCV(CreateView):
	model = Fletpercjellja
	template_name = 'invoice_system/fletpercjellja_create.html'
	fields = '__all__'

class FletpercjelljaLV(ListView):
	model = Fletpercjellja
	template_name = 'invoice_system/fletpercjellja_listview.html'
	context_object_name = 'fletpercjelliet'

def fletpercjellja_detail_view(request, f_id):

	fletpercjellja = Fletpercjellja.objects.get(fletpercjellja_id=f_id)
	shitjet = Shitje.objects.filter(fletpercjellja=f_id).order_by('id')

	form = ShitjeForm(f_id=f_id)
	if request.method == "POST":
		form = ShitjeForm(request.POST, f_id=f_id)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(f'/fletpercjellja_detail/{f_id}/')

	search_form = SearchGetFletpercjellja()
	if request.method=="POST":
		search_form = SearchGetFletpercjellja(request.POST)
		if search_form.is_valid():
			search_str = request.POST.get('search')
			if search_str:
				obj = get_object_or_404(Fletpercjellja, fletpercjellja_id=search_str)
				return HttpResponseRedirect(f'/fletpercjellja_detail/{search_str}/')

	next = None
	previous = None
	nextTrigger = False
	fletpercjelljet = Fletpercjellja.objects.all()

	for i in range(len(fletpercjelljet)):
		if fletpercjelljet[i] == fletpercjellja:
			nextTrigger = True
			if i != 0:
				previous = fletpercjelljet[i-1]
			continue
		if nextTrigger:
			next = fletpercjelljet[i]
			nextTrigger = False
			
		
	context = {
		"next": next,
		"previous": previous,
		"fletpercjellja": fletpercjellja,
		"shitjet": shitjet,
		"form": form,
		"search_form": search_form,
	}
	return render(request, 'invoice_system/fletpercjellja_detail.html', context)



class ProductDV(DetailView):
	model = Product
	template_name = 'invoice_system/produkt_detail.html'

	def post(self, request, *args, **kwargs):
		product_id = request.POST.get('product')
		try:
			product = Product.objects.get(product_id=product_id)
		except Product.DoesNotExist:
			product = self.kwargs['pk']
		
		return HttpResponseRedirect(f'/produkt_detail/{product}/')
	
	def get_context_data(self, **kwargs):
		context = super(ProductDV, self).get_context_data(**kwargs)
		context['shitjet'] = Shitje.objects.filter(product=self.kwargs['pk']).order_by('-id')
		context['produktet'] = Product.objects.all()
		return context


class ProductCV(CreateView):
	model = Product
	template_name = 'invoice_system/produkt_create.html'
	fields = '__all__'

class ProductUV(UpdateView):
	model = Product
	template_name = 'invoice_system/produkt_create.html'
	fields = '__all__'

class ProductDelete(DeleteView):
	model = Product
	template_name = 'invoice_system/delete_form.html'
	success_url = '/'

def produkt_listview(request):
	produktet = Product.objects.all()
	if request.method == 'POST':
		product_id = request.POST.get('product')
		return HttpResponseRedirect(f'/produkt_detail/{product_id}/')
	context = {'produktet': produktet}
	return render(request, 'invoice_system/produkt_listview.html', context)

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta>
	<!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>	

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js" integrity="sha256-+C0A5Ilqmu4QcSPxrlGpaZxJ04VjsRjKu+G82kl5UJk=" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css" integrity="sha256-ze/OEYGcFbPRmvCnrSeKbRTtjG4vGLHXgOqsyLFTRjg=" crossorigin="anonymous" />
	<title>{% block title %} {% endblock %}</title>

</head>


<body>

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		  <a class="navbar-brand" href="/">Dashboard</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
		    <div class="navbar-nav">
				<a class="nav-item nav-link " href="{% url 'fletpercjellja_listview_url'%}">Fletpercjelliet</a>
				<a class="nav-item nav-link" href="{% url 'produkt_listview_url' %}">Artikujt</a>
				<a class="nav-item nav-link" href="#">Faturat Hyrese</a>
			</div>
			<div class="navbar-nav">
				{% if request.user.is_authenticated %}
					<a class="nav-item nav-link text-primary"><b>{{ request.user }}</b></a>
					<a class="nav-item nav-link text-danger" href="/logout/">Log Out</a>
				{% else %}
					<a class="nav-item nav-link" href="/login/">Log In</a>
				{% endif %}
			</div>
		  </div>
	</nav>

	<br>
	
	<div class="container">

		{% if request.user.is_authenticated or request.path == '/login/' %}
			{% block content %}
			{% endblock %}
		{% else %}
		<div class="alert alert-danger">
			You don't have permission to view this content!
		</div>
		{% endif %}
	</div>

</body>

</html>

templates/invoice_system/dashboard.html
{% extends '../base.html' %}


{% block title %}Dashboard{% endblock %}

{% block content %}
	<div class="text-center">
		Welcome <b>{{ request.user }}</b>!
	</div>
{% endblock %}

templates/invoice_system/delete_form.html
{% extends '../base.html' %}

{% load crispy_forms_tags %}

{% block title %}Delete Form{% endblock %}


{% block content %}

<form method="post" class="form-group"> {% csrf_token %}
    <h1>Are you sure that you want to remove: {{ object.pk }}</h1>
    <button class="btn btn-danger">Delete</button>
    {% if 'produkt' in request.path %}
    <a href="{% url 'produkt_detail_url' object.pk %}" class="btn btn-dark">Cancel</a>
    {% else %}
    {% endif %}
</form>

{% endblock %}

templates/invoice_system/fletpercjellja_create.html
{% extends '../base.html' %}

{% load crispy_forms_tags %}

{% block title %}Krijo Fletpercjellje{% endblock %}


{% block content %}

<form method="post" class="form-group"> {% csrf_token %}
	{{ form | crispy }}
	<button type="submit" class="btn btn-success">Save</button>
</form>

{% endblock %}

templates/invoice_system/fletpercjellja_detail.html
{% extends '../base.html' %}

{% load crispy_forms_tags %}

{% block title %}Fletpercjellja: {{ fletpercjellja.fletpercjellja_id }}{% endblock %}


{% block content %}
<form method="POST"> {% csrf_token %}
	{{ search_form|crispy }}
	<button class="btn btn-success">Get</button>
</form>

<hr>
<div class="d-flex justify-content-between">
	{% if previous %}
	<div><- <a href="{% url 'fletpercjellja_detail_url' previous.pk %}">{{ previous.pk }}</a> </div>
	{% else %}
	<div></div>
	{% endif %}
	
	
	{% if next %}
	<div><a href="{% url 'fletpercjellja_detail_url' next.pk %}">{{ next.pk }}</a> -></div>
	{% endif %}
</div>
<hr>
<h1><span class="text-muted">Fletepercjellja </span> <span class="badge badge-danger">{{ fletpercjellja.fletpercjellja_id }}</span></h1>
<hr>
<h5><span class="text-muted">Data: </span>{{ fletpercjellja.fletpercjellja_data }}</h5>
<br>
{% if fletpercjellja.fletpercjellja_verejtje != '' %}
<h5><span class="text-muted text-danger">Verejtje: </span>{{ fletpercjellja.fletpercjellja_verejtje }}</h5>
<br>
{% endif %}
<h3><span class="text-muted">Totali: </span> <b class="badge badge-success">{{ fletpercjellja.get_total }}</b></h3>
<br>


<table class="table table-striped">
	<tr class="table-primary">
			<th>Artikulli ID</th>
			<th>Emri Artikullit</th>
			<th>Pershkrimi</th>
			<th>Sasia</th>
			<th>(Njesia)</th>
			<th>Cmimi</th>
			<th>Totali</th>
	</tr>
	{% for shitja in shitjet %}
	<tr>
		<td><a href="{% url 'produkt_detail_url' shitja.product.product_id %}" target="">{{ shitja.product }}</a></td>
		<td>{{ shitja.product.product_name }}</td>
		<td>{{ shitja.product.product_desc }}</td>
		<td>{{ shitja.shitje_quantity.normalize }}</td>
		<td><span class="badge badge-secondary">{{ shitja.product.product_unit }}</span></td>
		<td>{{ shitja.shitje_price }} €</td>
		<td><b>{{ shitja.totali }} €</b></td>
	</tr>

	{% endfor %}

	<tr class="table-success">
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td><span class="">{{ fletpercjellja.get_total }}</span></td>
	</tr>
</table>

<form method="post" class="form-group"> {% csrf_token %}
	{{ form.fletpercjellja | as_crispy_field }}
	{{ form.product | as_crispy_field }}
	{{ form.shitje_quantity | as_crispy_field }}
	{{ form.shitje_price | as_crispy_field }}
	<button type="submit" class="btn btn-success">Shto Artikullin +</button>
</form>

<script>
	$(document).ready(function () {
		$('#id_product').selectize({
			sortField: 'text'
	  	});
	});	
	
	document.getElementByName('fletpercjellja').style.color = "red";
</script>

{% endblock %} 

templates/invoice_system/fletpercjellja_listview.html
{% extends '../base.html' %}

{% load crispy_forms_tags %}

{% block title %}Fletpercjellja{% endblock %}


{% block content %}

<div class="d-flex justify-content-between">
	<h2>Fletpercjelljet</h2>
	<a href="{% url 'fletpercjellja_create_url' %}" class="btn-lg btn-primary">+</a>
</div>
<hr>
<ul>
{% for fletpercjellja in fletpercjelliet %}
	<li><a href="{% url 'fletpercjellja_detail_url' fletpercjellja.fletpercjellja_id %}">{{ fletpercjellja.fletpercjellja_id }} - {{ fletpercjellja.fletpercjellja_data | date:"d/m/Y" }}</a></li>
{% endfor %}
</ul>


{% endblock %} 

templates/invoice_system/produkt_create.html
{% extends '../base.html' %}

{% load crispy_forms_tags %}

{% block title %}Krijo Produktin{% endblock %}


{% block content %}

<form method="post" class="form-group"> {% csrf_token %}
	{{ form | crispy }}

	{% if 'produkt_update' in request.path %}
	<button type="submit" class="btn btn-warning">Update</button>
	{% else %}
	<button type="submit" class="btn btn-success">Shto Artikullin</button>
	{% endif %}
</form>

{% endblock %}

templates/invoice_system/produkt_detail.html
{% extends '../base.html' %}

{% load crispy_forms_tags %}

{% block title %}Produkti : {{ object.product_id }}{% endblock %}


{% block content %}

<form method="POST" id="select-form" class="form-group">{% csrf_token %}
	<select id="select" placeholder="Select a product" name="product" class="" onchange="this.form.submit()">
		<option value="">Select a product...</option>
		{% for produkt in produktet %}
		{% if produkt.product_id == object.product_id %}
			<option value="{{ produkt.product_id }}">{{ produkt.product_id }}</option>
		{% else %}
			<option value="{{ produkt.product_id }}">{{ produkt.product_id }}</option>
		{% endif %}
		{% endfor %}
	  
	</select>
</form>

<hr>

<div class="d-flex">
	<h1 class="mr-auto p-2">{{ object.product_id }}</h1>
	<div class="p-2">
		<div class="btn-group btn-group-sm">
			<a href="{% url 'produkt_update_url' object.product_id %}" class="btn btn-warning">Update</a>
			<a href="{% url 'produkt_delete_url' object.product_id %}" class="btn btn-danger">Delete</a>
		</div>
	</div>
	
</div>

<hr>

<table class="table">
	<tr class="table-secondary">
		<td>Produkti:</td>
		<td><b>{{ object.product_name }} {{ object.product_desc }}</b></td>
	</tr>

	<tr class="table-warning">
		<td>Cmimi Shites:</td>
		<td><b>{{ object.product_price }} €</b></td>
	</tr>

	<tr>
		<td></td>
		<td></td>
	</tr>

	<tr>
		<td>Njesia</td>
		<td><span class="badge badge-secondary">{{ object.product_unit }}</span></td>
	</tr>
	<tr>
		<td>Hyrje:</td>
		<td><b class="badge badge-success">{{ object.hyrje.normalize }}</b></td>
	</tr>

	<tr>
		<td>Dalje:</td>
		<td><b class="badge badge-danger">{{ object.dalje.normalize }}</b></td>
	</tr>

	<tr>
		<td>Sasia e mbetur:</td>
		<td><b class="badge badge-primary">{{ object.quantity.normalize }}</b></td>
	</tr>
</table>

<br> <br>

<br><br>

<h2>Shitjet</h2>
<hr>
<table class="table table-striped">
	<tr class="table-primary">
			<th>Fletpercjellja ID</th>
			<th>Emri Artikullit</th>
			<th>Pershkrimi</th>
			<th>Sasia</th>
			<th>Cmimi</th>
			<th>Totali</th>
	</tr>
	{% for shitja in shitjet %}
	<tr>
		<td><a href="{% url 'fletpercjellja_detail_url' shitja.fletpercjellja.fletpercjellja_id %}">{{ shitja.fletpercjellja }}</a></td>
		<td>{{ shitja.product.product_name }}</td>
		<td>{{ shitja.product.product_desc }}</td>
		<td>{{ shitja.shitje_quantity.normalize }} Copë</td>
		<td>{{ shitja.shitje_price }} €</td>
		<td><b>{{ shitja.totali }} €</b></td>
	</tr>

	{% endfor %}
</table>

<script>
	$(document).ready(function () {
		$('select').selectize({
			sortField: 'text'
	  	});
	});	
</script>


{% endblock %} 

templates/invoice_system/produkt_listview.html
{% extends '../base.html' %}

{% load crispy_forms_tags %}

{% block title %}Artikujt{% endblock %}


{% block content %}

<h2>Artikujt</h2>
<hr>


<form method="POST" id="select-form" class="form-group">{% csrf_token %}
	<select id="select" placeholder="Select a product" name="product" class="" onchange="this.form.submit()">
		<option value="">Select a product...</option>
		{% for produkt in produktet %}
		<option value="{{ produkt.product_id }}">{{ produkt.product_id }}</option>
		{% endfor %}
	  
	</select>
</form>

<ul>
{% for produkt in produktet %}
	<li><a href="{% url 'produkt_detail_url' produkt.product_id %}">{{ produkt.product_id }} - {{ produkt.product_name }} {{ produkt.product_desc }}</a></li>
{% endfor %}
</ul>

<script>
	$(document).ready(function () {
		$('select').selectize({
			sortField: 'text'
	  	});
	});	
</script>


{% endblock %} 